#!/usr/bin/env bun
/** Build the static microsite. PDF fitting/rendering is an explicit, confirmed mode. */

import { appendFileSync, cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, extname, join, relative, resolve, sep } from 'node:path';
import { createInterface } from 'node:readline/promises';
import { fileURLToPath } from 'node:url';
import { minify as minifyHtml } from 'html-minifier-terser';
import { transform as transformCss } from 'lightningcss';
import { chromium } from 'playwright';
import { generateOgImage } from './generate-og-image.js';
import {
  buildLlmsTxt,
  buildRobotsTxt,
  expandSitemapUrls,
  injectDiscoverabilityHtml
} from './discoverability.js';
import { A4_MEDIA_BOX, verifyPdf } from './pdf-verify.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const DIST = resolve(ROOT, 'dist');
const CACHE = resolve(ROOT, '.build-cache');
const PROFILE_SOURCE = resolve(CACHE, 'profiles.full.js');
const FIT_REPORT = resolve(CACHE, 'fit-report.json');
const PROGRESS_LOG = resolve(CACHE, 'build-progress.log');
const A4 = A4_MEDIA_BOX;
const PDF_MODE = process.argv.includes('--pdf');
const FIT_ONLY_MODE = process.argv.includes('--fit-only');
const PDF_CONFIRMED = process.argv.includes('--yes');
const PROFILE_ARG_INDEX = process.argv.indexOf('--profile');
const TARGET_PROFILE_ID = PROFILE_ARG_INDEX >= 0 ? process.argv[PROFILE_ARG_INDEX + 1] : '';

if (PROFILE_ARG_INDEX >= 0 && (!TARGET_PROFILE_ID || TARGET_PROFILE_ID.startsWith('--'))) {
  throw new Error('--profile requires a résumé profile id');
}
if (TARGET_PROFILE_ID && !PDF_MODE) {
  throw new Error('--profile is only supported with --pdf');
}

async function confirmPdfBuild() {
  if (!PDF_MODE || PDF_CONFIRMED || FIT_ONLY_MODE) return;
  if (!process.stdin.isTTY) {
    throw new Error('PDF generation requires explicit confirmation. Re-run with --pdf --yes.');
  }

  const prompt = createInterface({ input: process.stdin, output: process.stdout });
  try {
    const scope = TARGET_PROFILE_ID ? `the ${TARGET_PROFILE_ID} résumé PDF` : 'every résumé PDF';
    const answer = await prompt.question(`Generate and verify ${scope}? Continue? [y/N] `);
    if (!/^(?:y|yes)$/i.test(answer.trim())) {
      console.log('PDF generation cancelled; no build files were changed.');
      process.exit(0);
    }
  } finally {
    prompt.close();
  }
}

function assertInsideRoot(target) {
  const rel = relative(ROOT, target);
  if (!rel || rel.startsWith(`..${sep}`) || rel === '..' || rel.startsWith(sep)) {
    throw new Error(`Refusing to mutate path outside the project: ${target}`);
  }
}

function cleanDirectory(target, preserve = new Set()) {
  assertInsideRoot(target);
  mkdirSync(target, { recursive: true });
  /*
   * Preserve the directory inode: on Windows, a local preview process can retain
   * a directory handle after exiting and make rmSync(target) fail with EBUSY.
   * Removing validated children provides the same clean build without coupling
   * the pipeline to that stale handle.
  */
  for (const entry of readdirSync(target)) {
    if (preserve.has(entry)) continue;
    const child = join(target, entry);
    assertInsideRoot(child);
    rmSync(child, { recursive: true, force: true });
  }
}

function runBun(script, args = []) {
  const result = Bun.spawnSync(['bun', 'run', script, ...args], { cwd: ROOT, stdout: 'inherit', stderr: 'inherit' });
  if (result.exitCode !== 0) throw new Error(`${script} failed with exit code ${result.exitCode}`);
}

function progress(message) {
  appendFileSync(PROGRESS_LOG, `${new Date().toISOString()} ${message}\n`);
  console.log(message);
}

function parseProfiles(source) {
  const prefix = 'window.PROFILES = ';
  const start = source.indexOf(prefix);
  const end = source.lastIndexOf(';');
  if (start < 0 || end < 0) throw new Error('Compiler payload format is invalid');
  return JSON.parse(source.slice(start + prefix.length, end));
}

function parseCompiledPayload(source) {
  const aliasMatch = source.match(/window\.VARIANT_ALIASES\s*=\s*(\{[\s\S]*?\});/);
  const proofMatch = source.match(/window\.PROOF_ROUTER\s*=\s*(\[[\s\S]*?\]);\s*(?=window\.PROFILES)/);
  const revisionMatch = source.match(/\/\*\s*Source:\s*([^*]+)\s*\*\//);
  return {
    profiles: parseProfiles(source),
    variantAliases: aliasMatch ? JSON.parse(aliasMatch[1]) : {},
    proofRouter: proofMatch ? JSON.parse(proofMatch[1]) : [],
    sourceRevision: revisionMatch ? revisionMatch[1].trim() : ''
  };
}

function profileScript(profiles, variantAliases = {}, sourceRevision = '', proofRouter = []) {
  const header = `/* Generated by bun/src/build.js - do not edit. */\n` +
    (sourceRevision ? `/* Source: ${sourceRevision} */\n` : '');
  const aliases = Object.keys(variantAliases).length
    ? `window.VARIANT_ALIASES=${JSON.stringify(variantAliases)};\n`
    : '';
  const proofs = Array.isArray(proofRouter) && proofRouter.length
    ? `window.PROOF_ROUTER=${JSON.stringify(proofRouter)};\n`
    : 'window.PROOF_ROUTER=[];\n';
  return `${header}${aliases}${proofs}window.PROFILES=${JSON.stringify(profiles)};\n`;
}

function writeGatewayMetadata(profiles, sourceRevision = '', proofRouter = []) {
  const fallback = profiles.find(profile => profile.fallback) || profiles[0];
  let priorityIds = [];
  const priorityPath = resolve(ROOT, 'config/release-priority-variants.json');
  if (existsSync(priorityPath)) {
    priorityIds = JSON.parse(readFileSync(priorityPath, 'utf8')).variantIds || [];
  }

  const { xml: sitemap } = expandSitemapUrls(profiles, priorityIds, sourceRevision);
  writeFileSync(resolve(DIST, 'sitemap.xml'), sitemap);
  writeFileSync(resolve(DIST, 'robots.txt'), buildRobotsTxt());
  writeFileSync(resolve(DIST, 'llms.txt'), buildLlmsTxt({
    profile: fallback,
    proofs: proofRouter,
    sourceRevision,
    profileCount: profiles.length
  }));

  const indexPath = resolve(DIST, 'index.html');
  if (fallback && existsSync(indexPath)) {
    const injected = injectDiscoverabilityHtml(readFileSync(indexPath, 'utf8'), {
      profile: fallback,
      proofs: proofRouter,
      sourceRevision,
      profiles
    });
    writeFileSync(indexPath, injected);
  }
}

function contentType(pathname) {
  return ({
    '.css': 'text/css; charset=utf-8',
    '.html': 'text/html; charset=utf-8',
    '.js': 'text/javascript; charset=utf-8',
    '.json': 'application/json; charset=utf-8',
    '.pdf': 'application/pdf',
    '.png': 'image/png',
    '.ttf': 'font/ttf',
    '.woff2': 'font/woff2'
  })[extname(pathname).toLowerCase()] || 'application/octet-stream';
}

async function runChromium(args) {
  const process = Bun.spawn([chromium.executablePath(), '--headless', '--no-sandbox', '--disable-gpu', ...args], {
    cwd: ROOT,
    stdout: 'pipe',
    stderr: 'pipe'
  });
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(process.stdout).text(),
    new Response(process.stderr).text(),
    process.exited
  ]);
  if (exitCode !== 0) throw new Error(`Chromium exited ${exitCode}: ${stderr.trim()}`);
  return { stdout, stderr };
}

async function writeProductionAssets() {
  const typesettingSource = readFileSync(resolve(CACHE, 'typesetting.css'), 'utf8');
  const sourceTokens = readFileSync(resolve(ROOT, 'assets/css/tokens.css'), 'utf8');
  const sourceCss = readFileSync(resolve(ROOT, 'assets/css/style.css'), 'utf8');
  const lightning = { minify: true, targets: { chrome: 133 << 16 } };
  const tokens = transformCss({ filename: 'tokens.css', code: Buffer.from(sourceTokens), ...lightning }).code;
  const typesetting = transformCss({ filename: 'typesetting.css', code: Buffer.from(typesettingSource), ...lightning }).code;
  const css = transformCss({ filename: 'style.css', code: Buffer.from(sourceCss), ...lightning }).code;
  mkdirSync(resolve(DIST, 'assets/css'), { recursive: true });
  writeFileSync(resolve(DIST, 'assets/css/tokens.css'), tokens);
  writeFileSync(resolve(DIST, 'assets/css/typesetting.css'), typesetting);
  writeFileSync(resolve(DIST, 'assets/css/style.css'), css);

  const bundle = await Bun.build({
    entrypoints: [resolve(ROOT, 'assets/js/app.js')],
    outdir: resolve(DIST, 'assets/js'),
    naming: 'app.js',
    target: 'browser',
    minify: true,
    sourcemap: 'none'
  });
  if (!bundle.success) throw new Error(bundle.logs.map(log => log.message).join('\n'));

  mkdirSync(resolve(DIST, 'assets/fonts'), { recursive: true });
  mkdirSync(resolve(DIST, 'assets/img'), { recursive: true });
  const fontAssets = JSON.parse(readFileSync(resolve(ROOT, 'assets/fonts/font-manifest.json'), 'utf8'))
    .files
    .map(file => file.filename)
    .filter(filename => filename.endsWith('.woff2') || filename.endsWith('.ttf'));
  for (const fontAsset of fontAssets) {
    cpSync(resolve(ROOT, 'assets/fonts', fontAsset), resolve(DIST, 'assets/fonts', fontAsset), { recursive: false });
  }
  cpSync(resolve(ROOT, 'assets/img/logos'), resolve(DIST, 'assets/img/logos'), { recursive: true });
  cpSync(resolve(ROOT, 'assets/img/logo'), resolve(DIST, 'assets/img/logo'), { recursive: true });
  if (existsSync(resolve(ROOT, 'assets/img/og'))) {
    cpSync(resolve(ROOT, 'assets/img/og'), resolve(DIST, 'assets/img/og'), { recursive: true });
  }

  const html = await minifyHtml(readFileSync(resolve(ROOT, 'index.html'), 'utf8'), {
    collapseWhitespace: true,
    conservativeCollapse: true,
    removeComments: true,
    ignoreCustomComments: [/^COLD_SHEET_/],
    removeRedundantAttributes: true,
    sortAttributes: true,
    sortClassName: true
  });
  writeFileSync(resolve(DIST, 'index.html'), html);
  writeFileSync(resolve(DIST, 'CNAME'), 'resume.kartavya.tech\n');
  writeFileSync(resolve(DIST, '.nojekyll'), '');
}

async function writeShareAssets(fallbackProfile) {
  const output = resolve(DIST, 'assets/img/og-default.png');
  const trackedOg = resolve(ROOT, 'assets/img/og-default.png');
  const legacyOg = resolve(ROOT, 'assets/img/logo/logo_kj_og.png');
  if (process.env.OG_RENDER === '1') {
    try {
      await generateOgImage(DIST, fallbackProfile);
      progress('og-image-ready');
      return;
    } catch (error) {
      console.warn(`OG screenshot failed; copied fallback image (${error.message})`);
    }
  }
  if (existsSync(trackedOg)) {
    cpSync(trackedOg, output, { recursive: false });
    progress('og-image-ready');
    return;
  }
  if (existsSync(legacyOg)) {
    cpSync(legacyOg, output, { recursive: false });
    progress('og-image-ready');
    return;
  }
  throw new Error('Missing OG fallback image at assets/img/og-default.png');
}

async function verifyRenderedPdf(path, profile) {
  await verifyPdf(path, {
    label: profile.id,
    expectedPageCount: 1,
    expectedTitle: profile.name
  });
}

await confirmPdfBuild();

/* Fast builds retain the last confirmed PDF batch instead of regenerating it. */
cleanDirectory(DIST, PDF_MODE && !TARGET_PROFILE_ID ? new Set() : new Set(['resumes']));
cleanDirectory(CACHE, new Set(['preview_server.py', 'preview-server.out.log', 'preview-server.err.log']));
runBun('bun/src/validate.js');
runBun('bun/src/font-metrics.js');
runBun('bun/src/compile.js', ['--out', relative(ROOT, PROFILE_SOURCE)]);
await writeProductionAssets();
progress('assets-ready');

const compiledPayload = parseCompiledPayload(readFileSync(PROFILE_SOURCE, 'utf8'));
const fullProfiles = compiledPayload.profiles;
const variantAliases = compiledPayload.variantAliases;
const proofRouter = compiledPayload.proofRouter || [];
const sourceRevision = compiledPayload.sourceRevision;
const buildProfiles = TARGET_PROFILE_ID
  ? fullProfiles.filter(profile => profile.id === TARGET_PROFILE_ID)
  : fullProfiles;
if (TARGET_PROFILE_ID && buildProfiles.length !== 1) {
  throw new Error(`Unknown résumé profile: ${TARGET_PROFILE_ID}`);
}
mkdirSync(resolve(DIST, 'public'), { recursive: true });
writeFileSync(resolve(DIST, 'public/data.js'), profileScript(PDF_MODE ? buildProfiles : fullProfiles, variantAliases, sourceRevision, proofRouter));

if (!PDF_MODE && !FIT_ONLY_MODE) {
  for (const profile of fullProfiles) {
    profile.pdfAvailable = Boolean(profile.pdfFilename && existsSync(resolve(DIST, 'resumes', profile.pdfFilename)));
  }
  writeFileSync(resolve(DIST, 'public/data.js'), profileScript(fullProfiles, variantAliases, sourceRevision, proofRouter));
  const fallbackProfile = fullProfiles.find(profile => profile.fallback) || fullProfiles[0];
  await writeShareAssets(fallbackProfile);
  writeGatewayMetadata(fullProfiles, sourceRevision, proofRouter);
  const retainedPdfs = fullProfiles.filter(profile => profile.pdfAvailable).length;
  const priorityPath = resolve(ROOT, 'config/release-priority-variants.json');
  const priorityIds = existsSync(priorityPath)
    ? JSON.parse(readFileSync(priorityPath, 'utf8')).variantIds || []
    : [];
  const priorityMissing = priorityIds.filter(id => {
    const profile = fullProfiles.find(entry => entry.id === id);
    return profile && !profile.pdfAvailable;
  });
  writeFileSync(resolve(DIST, 'build-report.json'), `${JSON.stringify({
    profiles: fullProfiles.length,
    pdfs: retainedPdfs,
    pdfGeneration: 'skipped; explicit confirmation required',
    priorityVariants: priorityIds.length,
    priorityMissingPdfs: priorityMissing
  }, null, 2)}\n`);
  console.log(`✓ Built site and ${fullProfiles.length} résumé profiles; PDF generation skipped (${retainedPdfs} retained) → dist/`);
  process.exit(0);
}

if (FIT_ONLY_MODE && !PDF_MODE) {
  for (const profile of fullProfiles) {
    profile.pdfAvailable = Boolean(profile.pdfFilename && existsSync(resolve(DIST, 'resumes', profile.pdfFilename)));
  }
  writeFileSync(resolve(DIST, 'public/data.js'), profileScript(fullProfiles, variantAliases, sourceRevision, proofRouter));
  writeGatewayMetadata(fullProfiles, sourceRevision, proofRouter);
}

const server = Bun.serve({
  port: 0,
  async fetch(request) {
    const url = new URL(request.url);
    const requested = decodeURIComponent(url.pathname === '/' ? '/index.html' : url.pathname);
    const filePath = resolve(DIST, `.${requested}`);
    const rel = relative(DIST, filePath);
    if (rel.startsWith('..') || !existsSync(filePath)) return new Response('Not found', { status: 404 });
    return new Response(Bun.file(filePath), { headers: { 'content-type': contentType(filePath), 'cache-control': 'no-store' } });
  }
});

try {
  progress('chromium-fit-started');
  const fitUrl = `${server.url}?_fit=1&_fitAll=1`;
  const dump = await runChromium(['--virtual-time-budget=5000', '--dump-dom', fitUrl]);
  const fitMatch = dump.stdout.match(/<pre[^>]+id="fit-output"[^>]*>([A-Za-z0-9+/=]+)<\/pre>/);
  if (!fitMatch) {
    const errorMatch = dump.stdout.match(/data-fit-error="([^"]+)"/);
    throw new Error(`Chromium did not return fitted profiles${errorMatch ? `: ${errorMatch[1]}` : ''}`);
  }
  const fitResults = JSON.parse(Buffer.from(fitMatch[1], 'base64').toString('utf8'));
  if (fitResults.length !== buildProfiles.length) throw new Error('Chromium fit result count does not match source profiles');

  const fittedProfiles = [];
  const reports = [];
  for (let index = 0; index < fitResults.length; index += 1) {
    const profile = buildProfiles[index];
    const result = fitResults[index];
    result.profile.pdfAvailable = FIT_ONLY_MODE
      ? Boolean(result.profile.pdfFilename && existsSync(resolve(DIST, 'resumes', result.profile.pdfFilename)))
      : true;
    fittedProfiles.push(result.profile);
    reports.push({
      id: profile.id,
      role: profile.role,
      industry: profile.industry,
      category: profile.category,
      passes: result.passes,
      omissions: result.omissions,
      measurement: result.measurement
    });
    progress(`fit ${profile.id}: ${result.passes} pass(es), ${result.omissions.length} omission(s)`);
  }

  writeFileSync(FIT_REPORT, `${JSON.stringify(reports, null, 2)}\n`);
  progress('fit-complete');

  const publishedProfiles = FIT_ONLY_MODE
    ? fullProfiles.map(profile => {
      const fitted = fittedProfiles.find(entry => entry.id === profile.id);
      if (!fitted) return profile;
      fitted.pdfAvailable = Boolean(fitted.pdfFilename && existsSync(resolve(DIST, 'resumes', fitted.pdfFilename)));
      return fitted;
    })
    : fittedProfiles;

  writeFileSync(resolve(DIST, 'public/data.js'), profileScript(publishedProfiles, variantAliases, sourceRevision, proofRouter));
  const fallbackProfile = publishedProfiles.find(profile => profile.fallback) || publishedProfiles[0];
  await writeShareAssets(fallbackProfile);
  writeGatewayMetadata(publishedProfiles, sourceRevision, proofRouter);

  const totalOmissions = reports.reduce((sum, report) => sum + report.omissions.length, 0);
  const reportSummary = {
    mode: FIT_ONLY_MODE ? 'fit-only' : 'pdf',
    profiles: fittedProfiles.length,
    pdfs: FIT_ONLY_MODE ? publishedProfiles.filter(profile => profile.pdfAvailable).length : fittedProfiles.length,
    totalOmissions,
    maximumFitPasses: Math.max(...reports.map(report => report.passes)),
    metrics: JSON.parse(readFileSync(resolve(CACHE, 'font-metrics.json'), 'utf8'))
  };
  writeFileSync(resolve(DIST, 'build-report.json'), `${JSON.stringify(reportSummary, null, 2)}\n`);

  if (FIT_ONLY_MODE) {
    const overfit = reports.filter(report => report.passes > 6 || report.omissions.length > 8);
    if (overfit.length) {
      console.warn(`warning: ${overfit.length} profile(s) needed heavy fitting`);
    }
    console.log(`✓ Measured A4 fit for ${fittedProfiles.length} profiles (${totalOmissions} omission(s)) → ${relative(ROOT, FIT_REPORT)}`);
  } else {
    mkdirSync(resolve(DIST, 'resumes'), { recursive: true });

  const renderPdf = async profile => {
    const output = resolve(DIST, 'resumes', profile.pdfFilename);
    const renderUrl = `${server.url}?_fit=1&_profile=${encodeURIComponent(profile.id)}`;
    await runChromium([
      '--virtual-time-budget=750',
      '--print-to-pdf-no-header',
      '--no-pdf-header-footer',
      '--export-tagged-pdf',
      `--print-to-pdf=${output}`,
      renderUrl
    ]);
    await verifyRenderedPdf(output, profile);
    progress(`pdf ${profile.pdfFilename}`);
  };

  const PDF_CONCURRENCY = 8;
  for (let index = 0; index < fittedProfiles.length; index += PDF_CONCURRENCY) {
    await Promise.all(fittedProfiles.slice(index, index + PDF_CONCURRENCY).map(renderPdf));
  }

  if (TARGET_PROFILE_ID) {
    const fittedById = new Map(fittedProfiles.map(profile => [profile.id, profile]));
    const publishedProfiles = fullProfiles.map(profile => {
      const published = fittedById.get(profile.id) || profile;
      published.pdfAvailable = Boolean(published.pdfFilename && existsSync(resolve(DIST, 'resumes', published.pdfFilename)));
      return published;
    });
    writeFileSync(resolve(DIST, 'public/data.js'), profileScript(publishedProfiles, variantAliases, sourceRevision, proofRouter));
  }

  reportSummary.pdfs = fittedProfiles.length;
  writeFileSync(resolve(DIST, 'build-report.json'), `${JSON.stringify(reportSummary, null, 2)}\n`);
  console.log(`✓ Built ${fittedProfiles.length} fitted profile${fittedProfiles.length === 1 ? '' : 's'} and ${fittedProfiles.length} verified A4 PDF${fittedProfiles.length === 1 ? '' : 's'} → dist/`);
  }
} finally {
  server.stop(true);
}
