#!/usr/bin/env bun
/** Build the static microsite, fit every profile to one A4 page, and render its PDF. */

import { appendFileSync, cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, extname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { minify as minifyHtml } from 'html-minifier-terser';
import { transform as transformCss } from 'lightningcss';
import { PDFDocument } from 'pdf-lib';
import { chromium } from 'playwright';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const DIST = resolve(ROOT, 'dist');
const CACHE = resolve(ROOT, '.build-cache');
const PROFILE_SOURCE = resolve(CACHE, 'profiles.full.js');
const FIT_REPORT = resolve(CACHE, 'fit-report.json');
const PROGRESS_LOG = resolve(CACHE, 'build-progress.log');
const A4 = { width: 595.276, height: 841.89 };

function assertInsideRoot(target) {
  const rel = relative(ROOT, target);
  if (!rel || rel.startsWith(`..${sep}`) || rel === '..' || rel.startsWith(sep)) {
    throw new Error(`Refusing to mutate path outside the project: ${target}`);
  }
}

function cleanDirectory(target) {
  assertInsideRoot(target);
  rmSync(target, { recursive: true, force: true });
  mkdirSync(target, { recursive: true });
}

function runBun(script, args = []) {
  const result = Bun.spawnSync(['bun', 'run', script, ...args], { cwd: ROOT, stdout: 'inherit', stderr: 'inherit' });
  if (result.exitCode !== 0) throw new Error(`${script} failed with exit code ${result.exitCode}`);
}

function progress(message) {
  appendFileSync(PROGRESS_LOG, `${new Date().toISOString()} ${message}\n`);
  console.log(message);
}

function parseProfiles(source) {
  const prefix = 'window.PROFILES = ';
  const start = source.indexOf(prefix);
  const end = source.lastIndexOf(';');
  if (start < 0 || end < 0) throw new Error('Compiler payload format is invalid');
  return JSON.parse(source.slice(start + prefix.length, end));
}

function profileScript(profiles) {
  return `/* Generated by bun/src/build.js — do not edit. */\nwindow.PROFILES=${JSON.stringify(profiles)};\n`;
}

function escapeHtml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function roleSlug(role) {
  return role.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

async function writeSeoPages(profiles) {
  const groups = new Map();
  for (const profile of profiles) {
    if (!groups.has(profile.role)) groups.set(profile.role, []);
    groups.get(profile.role).push(profile);
  }

  const style = `@font-face{font-family:Resume;src:url(../../assets/fonts/source-serif-4-variable-roman.woff2) format('woff2-variations');font-weight:200 900}*{box-sizing:border-box}body{margin:0;background:#0d0d0d;color:#f5f5f5;font-family:system-ui,sans-serif}main{max-width:850px;margin:auto;padding:64px 24px 96px}a{color:#75d7ca}h1,h2{font-family:Resume,serif;font-weight:400}h1{font-size:42px;margin:.4em 0}h2{margin-top:2em}p,li{line-height:1.65}.eyebrow{color:#75d7ca;text-transform:uppercase;letter-spacing:.12em}.cards{display:grid;gap:12px;padding:0;list-style:none}.cards a{display:block;padding:16px;border:1px solid #333;border-radius:6px;text-decoration:none}.muted{color:#aaa}`;
  const indexItems = [...groups.keys()].sort().map(role => `<li><a href="${roleSlug(role)}/">${escapeHtml(role)}</a></li>`).join('');
  const indexHtml = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="description" content="Browse Kartavya Jharwal's role-focused resume profiles and downloadable PDFs."><link rel="canonical" href="https://resume.kartavya.tech/roles/"><title>Role-focused résumés — Kartavya Jharwal</title><style>${style.replaceAll('../..', '..')}</style></head><body><main><a href="../">← Interactive résumé</a><p class="eyebrow">Role index</p><h1>Kartavya Jharwal</h1><p>Explore focused résumé profiles built from one cross-domain career record.</p><ul class="cards">${indexItems}</ul></main></body></html>`;
  mkdirSync(resolve(DIST, 'roles'), { recursive: true });
  writeFileSync(resolve(DIST, 'roles/index.html'), await minifyHtml(indexHtml, { collapseWhitespace: true, removeComments: true }));

  const sitemapUrls = ['https://resume.kartavya.tech/', 'https://resume.kartavya.tech/roles/'];
  for (const [role, roleProfiles] of groups) {
    const slug = roleSlug(role);
    const industries = roleProfiles.map(profile => profile.industry);
    const skills = [...new Set(roleProfiles.flatMap(profile => profile.additional?.skills || []))].slice(0, 20);
    const experience = [];
    const seenExperience = new Set();
    for (const profile of roleProfiles) {
      for (const entry of profile.experience || []) {
        const key = `${entry.company}|${entry.role}`;
        if (!seenExperience.has(key)) {
          seenExperience.add(key);
          experience.push(entry);
        }
      }
    }
    const profileLinks = roleProfiles.map(profile => `<li><a href="../../?role=${encodeURIComponent(profile.role)}&amp;industry=${encodeURIComponent(profile.industry)}">${escapeHtml(profile.industry)} interactive résumé</a> · <a href="../../resumes/${encodeURIComponent(profile.pdfFilename)}">PDF</a></li>`).join('');
    const experienceHtml = experience.slice(0, 6).map(entry => `<li><strong>${escapeHtml(entry.role)}</strong>, ${escapeHtml(entry.company)}${entry.highlights?.[0] ? ` — ${escapeHtml(entry.highlights[0])}` : ''}</li>`).join('');
    const description = roleProfiles[0].summary || `Kartavya Jharwal's ${role} résumé across ${industries.join(', ')}.`;
    const canonical = `https://resume.kartavya.tech/roles/${slug}/`;
    const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="description" content="${escapeHtml(description.slice(0, 155))}"><link rel="canonical" href="${canonical}"><title>${escapeHtml(role)} résumé — Kartavya Jharwal</title><style>${style}</style></head><body><main><a href="../">← All roles</a> · <a href="../../">Interactive résumé</a><p class="eyebrow">Role-focused résumé</p><h1>${escapeHtml(role)}</h1><p>${escapeHtml(description)}</p><p class="muted">Industries: ${escapeHtml(industries.join(', '))}</p><h2>Relevant experience</h2><ul>${experienceHtml}</ul><h2>Skills and keywords</h2><p>${escapeHtml(skills.join(', '))}</p><h2>Choose an industry</h2><ul>${profileLinks}</ul></main></body></html>`;
    const dir = resolve(DIST, 'roles', slug);
    mkdirSync(dir, { recursive: true });
    writeFileSync(resolve(dir, 'index.html'), await minifyHtml(html, { collapseWhitespace: true, removeComments: true }));
    sitemapUrls.push(canonical);
  }

  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${sitemapUrls.map(url => `  <url><loc>${url}</loc></url>`).join('\n')}\n</urlset>\n`;
  writeFileSync(resolve(DIST, 'sitemap.xml'), sitemap);
  writeFileSync(resolve(DIST, 'robots.txt'), 'User-agent: *\nAllow: /\nSitemap: https://resume.kartavya.tech/sitemap.xml\n');
}

function contentType(pathname) {
  return ({
    '.css': 'text/css; charset=utf-8',
    '.html': 'text/html; charset=utf-8',
    '.js': 'text/javascript; charset=utf-8',
    '.json': 'application/json; charset=utf-8',
    '.pdf': 'application/pdf',
    '.png': 'image/png',
    '.woff2': 'font/woff2'
  })[extname(pathname).toLowerCase()] || 'application/octet-stream';
}

async function runChromium(args) {
  const process = Bun.spawn([chromium.executablePath(), '--headless', '--no-sandbox', '--disable-gpu', ...args], {
    cwd: ROOT,
    stdout: 'pipe',
    stderr: 'pipe'
  });
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(process.stdout).text(),
    new Response(process.stderr).text(),
    process.exited
  ]);
  if (exitCode !== 0) throw new Error(`Chromium exited ${exitCode}: ${stderr.trim()}`);
  return { stdout, stderr };
}

async function writeProductionAssets() {
  const metricsCss = readFileSync(resolve(CACHE, 'font-metrics.css'), 'utf8');
  const sourceCss = readFileSync(resolve(ROOT, 'assets/css/style.css'), 'utf8');
  const css = transformCss({
    filename: 'style.css',
    code: Buffer.from(`${metricsCss}\n${sourceCss}`),
    minify: true,
    targets: { chrome: 120 << 16 }
  }).code;
  mkdirSync(resolve(DIST, 'assets/css'), { recursive: true });
  writeFileSync(resolve(DIST, 'assets/css/style.css'), css);

  const bundle = await Bun.build({
    entrypoints: [resolve(ROOT, 'assets/js/app.js')],
    outdir: resolve(DIST, 'assets/js'),
    naming: 'app.js',
    target: 'browser',
    minify: true,
    sourcemap: 'none'
  });
  if (!bundle.success) throw new Error(bundle.logs.map(log => log.message).join('\n'));

  mkdirSync(resolve(DIST, 'assets/fonts'), { recursive: true });
  mkdirSync(resolve(DIST, 'assets/img'), { recursive: true });
  cpSync(resolve(ROOT, 'assets/fonts/source-serif-4-variable-roman.woff2'), resolve(DIST, 'assets/fonts/source-serif-4-variable-roman.woff2'), { recursive: false });
  cpSync(resolve(ROOT, 'assets/fonts/source-serif-4-variable-italic.woff2'), resolve(DIST, 'assets/fonts/source-serif-4-variable-italic.woff2'), { recursive: false });
  cpSync(resolve(ROOT, 'assets/img/logos'), resolve(DIST, 'assets/img/logos'), { recursive: true });

  const html = await minifyHtml(readFileSync(resolve(ROOT, 'index.html'), 'utf8'), {
    collapseWhitespace: true,
    conservativeCollapse: true,
    removeComments: true,
    removeRedundantAttributes: true,
    sortAttributes: true,
    sortClassName: true
  });
  writeFileSync(resolve(DIST, 'index.html'), html);
  writeFileSync(resolve(DIST, 'CNAME'), 'resume.kartavya.tech\n');
  writeFileSync(resolve(DIST, '.nojekyll'), '');
}

async function verifyPdf(path, expectedTitle) {
  const bytes = readFileSync(path);
  const pdf = await PDFDocument.load(bytes);
  if (pdf.getPageCount() !== 1) throw new Error(`${expectedTitle}: PDF must contain exactly one page`);
  const { width, height } = pdf.getPage(0).getSize();
  if (Math.abs(width - A4.width) > 0.5 || Math.abs(height - A4.height) > 0.5) {
    throw new Error(`${expectedTitle}: expected A4 MediaBox, got ${width.toFixed(2)}×${height.toFixed(2)}pt`);
  }
}

cleanDirectory(DIST);
cleanDirectory(CACHE);
runBun('bun/src/validate.js');
runBun('bun/src/font-metrics.js');
runBun('bun/src/compile.js', ['--out', relative(ROOT, PROFILE_SOURCE)]);
await writeProductionAssets();
progress('assets-ready');

const fullProfiles = parseProfiles(readFileSync(PROFILE_SOURCE, 'utf8'));
mkdirSync(resolve(DIST, 'public'), { recursive: true });
writeFileSync(resolve(DIST, 'public/data.js'), profileScript(fullProfiles));

const server = Bun.serve({
  port: 0,
  async fetch(request) {
    const url = new URL(request.url);
    const requested = decodeURIComponent(url.pathname === '/' ? '/index.html' : url.pathname);
    const filePath = resolve(DIST, `.${requested}`);
    const rel = relative(DIST, filePath);
    if (rel.startsWith('..') || !existsSync(filePath)) return new Response('Not found', { status: 404 });
    return new Response(Bun.file(filePath), { headers: { 'content-type': contentType(filePath), 'cache-control': 'no-store' } });
  }
});

try {
  progress('chromium-fit-started');
  const fitUrl = `${server.url}?_fit=1&_fitAll=1`;
  const dump = await runChromium(['--virtual-time-budget=5000', '--dump-dom', fitUrl]);
  const fitMatch = dump.stdout.match(/<pre[^>]+id="fit-output"[^>]*>([A-Za-z0-9+/=]+)<\/pre>/);
  if (!fitMatch) {
    const errorMatch = dump.stdout.match(/data-fit-error="([^"]+)"/);
    throw new Error(`Chromium did not return fitted profiles${errorMatch ? `: ${errorMatch[1]}` : ''}`);
  }
  const fitResults = JSON.parse(Buffer.from(fitMatch[1], 'base64').toString('utf8'));
  if (fitResults.length !== fullProfiles.length) throw new Error('Chromium fit result count does not match source profiles');

  const fittedProfiles = [];
  const reports = [];
  for (let index = 0; index < fitResults.length; index += 1) {
    const profile = fullProfiles[index];
    const result = fitResults[index];
    result.profile.pdfAvailable = true;
    fittedProfiles.push(result.profile);
    reports.push({
      id: profile.id,
      role: profile.role,
      industry: profile.industry,
      passes: result.passes,
      omissions: result.omissions,
      measurement: result.measurement
    });
    progress(`fit ${profile.id}: ${result.passes} pass(es), ${result.omissions.length} omission(s)`);
  }

  writeFileSync(FIT_REPORT, `${JSON.stringify(reports, null, 2)}\n`);
  progress('fit-complete');
  writeFileSync(resolve(DIST, 'public/data.js'), profileScript(fittedProfiles));
  await writeSeoPages(fittedProfiles);
  mkdirSync(resolve(DIST, 'resumes'), { recursive: true });

  const renderPdf = async profile => {
    const output = resolve(DIST, 'resumes', profile.pdfFilename);
    const renderUrl = `${server.url}?_fit=1&_profile=${encodeURIComponent(profile.id)}`;
    await runChromium([
      '--virtual-time-budget=750',
      '--print-to-pdf-no-header',
      '--no-pdf-header-footer',
      '--export-tagged-pdf',
      `--print-to-pdf=${output}`,
      renderUrl
    ]);
    await verifyPdf(output, profile.id);
    progress(`pdf ${profile.pdfFilename}`);
  };

  const PDF_CONCURRENCY = 8;
  for (let index = 0; index < fittedProfiles.length; index += PDF_CONCURRENCY) {
    await Promise.all(fittedProfiles.slice(index, index + PDF_CONCURRENCY).map(renderPdf));
  }

  const totalOmissions = reports.reduce((sum, report) => sum + report.omissions.length, 0);
  const reportSummary = {
    profiles: fittedProfiles.length,
    pdfs: fittedProfiles.length,
    totalOmissions,
    maximumFitPasses: Math.max(...reports.map(report => report.passes)),
    metrics: JSON.parse(readFileSync(resolve(CACHE, 'font-metrics.json'), 'utf8'))
  };
  writeFileSync(resolve(DIST, 'build-report.json'), `${JSON.stringify(reportSummary, null, 2)}\n`);
  console.log(`✓ Built ${fittedProfiles.length} fitted profiles and ${fittedProfiles.length} verified A4 PDFs → dist/`);
} finally {
  server.stop(true);
}
