#!/usr/bin/env bun
/** Extract the typeface constants required by TYPESETTING.md v1.5. */

import * as fontkit from 'fontkit';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const BUILD = resolve(ROOT, '.build-cache');
const FONT_PATH = resolve(ROOT, 'assets/fonts/source-serif-4-variable-roman.ttf');
const RESUME_PATH = resolve(ROOT, 'data/resume.json');

const UNIT_PT = 14;
const BODY_PT = 11;
const NAME_PT = 16;
const REQUIRED_FEATURES = ['case', 'liga', 'lnum', 'onum', 'pnum', 'smcp', 'tnum'];

const baseFont = fontkit.openSync(FONT_PATH);
const font = baseFont.getVariation({ wght: 400, opsz: BODY_PT });
const features = new Set(baseFont.availableFeatures || []);
const missingFeatures = REQUIRED_FEATURES.filter(feature => !features.has(feature));
const axes = baseFont.variationAxes || {};

if (missingFeatures.length) {
  throw new Error(`Typeface is missing required OpenType features: ${missingFeatures.join(', ')}`);
}
if (!axes.opsz || !axes.wght) {
  throw new Error('Typeface must expose both opsz and wght variation axes.');
}

const resume = JSON.parse(readFileSync(RESUME_PATH, 'utf8'));
const formatDate = value => {
  if (!value) return 'Present';
  const [year, month] = value.split('-');
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return month ? `${months[Number(month) - 1]} ${year}` : year;
};
const dateSamples = [...(resume.work || []), ...(resume.education || [])]
  .map(entry => `${formatDate(entry.startDate)} to ${formatDate(entry.endDate)}`);
const measuredDates = dateSamples.map(text => {
  const run = font.layout(text, ['tnum', 'lnum']);
  const units = run.positions.reduce((sum, position) => sum + position.xAdvance, 0);
  return { text, widthPt: (units / font.unitsPerEm) * BODY_PT };
});
const widestDate = measuredDates.sort((a, b) => b.widthPt - a.widthPt)[0];
const dateWidthPt = widestDate.widthPt;
const halfUnitPt = UNIT_PT / 2;
const dateReservedPt = Math.ceil(dateWidthPt / halfUnitPt) * halfUnitPt;

const bullet = font.glyphForCodePoint(0x2022);
const bulletLsbEm = bullet.bbox.minX / font.unitsPerEm;
const capOffsetPt = ((font.ascent - font.capHeight) / font.unitsPerEm) * NAME_PT;
const xHeightEm = font.xHeight / font.unitsPerEm;

const resumeText = JSON.stringify(resume).normalize('NFC');
const unsupportedCodePoints = [...new Set([...resumeText]
  .map(character => character.codePointAt(0))
  .filter(codePoint => codePoint > 0x7f && !font.hasGlyphForCodePoint(codePoint)))]
  .map(codePoint => `U+${codePoint.toString(16).toUpperCase().padStart(4, '0')}`);

if (unsupportedCodePoints.length) {
  throw new Error(`Typeface does not cover resume code points: ${unsupportedCodePoints.join(', ')}`);
}

const metrics = {
  family: baseFont.fullName,
  unitsPerEm: font.unitsPerEm,
  variation: { wght: 400, opsz: BODY_PT },
  availableFeatures: [...features].sort(),
  dateSample: widestDate.text,
  dateMeasuredPt: Number(dateWidthPt.toFixed(3)),
  dateReservedPt,
  bulletLsbEm: Number(bulletLsbEm.toFixed(2)),
  capOffsetPt: Number(capOffsetPt.toFixed(2)),
  xHeightEm: Number(xHeightEm.toFixed(3)),
  unsupportedCodePoints
};

  const css = `/* Generated by bun/src/font-metrics.js - do not edit. */\n` +
  `:root {\n` +
  `  --date-reserved-width: ${metrics.dateReservedPt}pt;\n` +
  `  --hang-bullet: ${metrics.bulletLsbEm.toFixed(2)}em;\n` +
  `  --cap-offset-s2: ${metrics.capOffsetPt.toFixed(2)}pt;\n` +
  `  --font-x-height: ${metrics.xHeightEm.toFixed(3)}em;\n` +
  `}\n`;

mkdirSync(BUILD, { recursive: true });
writeFileSync(resolve(BUILD, 'font-metrics.json'), `${JSON.stringify(metrics, null, 2)}\n`);
writeFileSync(resolve(BUILD, 'font-metrics.css'), css);

console.log(`✓ Extracted font metrics: date ${metrics.dateMeasuredPt}pt → ${metrics.dateReservedPt}pt, bullet LSB ${metrics.bulletLsbEm.toFixed(2)}em`);
